name: Build project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean jar